name: "ck_project"
version: "1.0"
config-version: 2

profile: "ck_project"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ck_project:
    +on_schema_change: append_new_columns
    silver:
      +materialized: incremental