name: "ck_project"
version: "1.0"
config-version: 2

profile: "ck_project"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  dim_date_start: '2000-01-01'
  dim_date_end:   '2040-12-31'

models:
  +persist_docs:
    relation: true
    columns: true

  ck_project:
    +on_schema_change: append_new_columns

    # BRONZE (if you have it as models)
    bronze:
      +database: bronze
      +schema: bronze
      +materialized: incremental
      +tags: ["bronze"]

    # SILVER
    silver:
      +database: silver          # <<<<<<<<<< important for ClickHouse
      +schema: silver
      +materialized: incremental
      +tags: ["silver"]

    # GOLD
    gold:
      +database: gold 
      +schema: gold           # <<<<<<<<<< important for ClickHouse
      +on-run-start:
        - "CREATE DATABASE IF NOT EXISTS gold"
      dim:
        +materialized: table
        +tags: ["gold_dim"]
        +engine: "MergeTree()"
      fact:
        +materialized: incremental
        +incremental_strategy: "delete+insert"
        +engine: "MergeTree()"