# dbt_project/profiles.yml
ck_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse-server
      port: 9000
      user: default
      password: ""
      secure: False
      schema: silver         # <- neutral; adapter may concatenate, so keep it simple
      threads: 4