# dbt_project/profiles.yml
# dbt_project/profiles.yml

ck_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse-server') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '9000') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'password') }}"
      secure: False
      database: "{{ env_var('CLICKHOUSE_DB', 'default') }}"
      schema: "{{ env_var('CLICKHOUSE_DB', 'default') }}"
      threads: 4
